version: "3.3"
services:
  uptime-kuma:
    # Pin image for reproducibility. Override with KUMA_TAG in .env
    # Example: KUMA_TAG=1.23.0
    image: louislam/uptime-kuma:${KUMA_TAG:-1}
    container_name: uptime-kuma
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - kuma-data:/app/data
    ports:
      - "${KUMA_HOST_PORT:-8010}:3001"
    restart: unless-stopped

volumes:
  kuma-data:
